#
# The repo you created from this template
# e.g. https://github.com/k8s-at-home/home-cluster
homelab_git_repository: ""
#
# The git branch you create from this template
homelab_git_branch: "main"
#
homelab_git_secret_name: ""
#
# Set value to true if you use a multi environment for flux
homelab_multi_env: false
#
# Optional: Enable GitHub to send a webhook to update Flux, set the following to one of:
# ignored - this feature will be disabled
# generated - this will generate a token and print it in the logs
# Set this to any other string and it will be used for the secret
homelab_github_webhook_secret: ""
#
# Choose one of your cloudflare domains
# e.g. k8s-at-home.com
homelab_cloudflare_domain: ""
# The email you use to sign into Cloudflare with
homelab_cloudflare_email: ""
# Your global Cloudflare API Key
homelab_cloudflare_apikey: ""
#
#
#
# Pick a range of unused IPs that are on the same network as your nodes
# You don't need many IPs, just choose 10 IPs to start with
# e.g. 192.168.1.220-192.168.1.230
homelab_metallb_lb_range: ""
#
# The load balancer IP for k8s_gateway, choose from one of the available IPs above
# e.g. 192.168.1.220
homelab_metallb_k8s_gateway_address: ""
#
# The load balancer IP for traefik, choose from one of the available IPs above
# that doesn't conflict with any other IP addresses here
# e.g. 192.168.1.221
homelab_metallb_traefik_address: ""
#
# Age Public Key - string should start with age
# e.g. age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
homelab_age_public_key: ""
#
# The IP Address to use with KubeVIP
# Pick a unused IP that is on the same network as your nodes
# and outside the ${BOOTSTRAP_METALLB_LB_RANGE} range
# and doesn't conflict with any other IP addresses here
# e.g. 192.168.1.254
homelab_kube_vip_address: ""
#
#
# Ansible related variables
#
#
# Default prefixes for hostnames assigned by Ansible
# These are unused on nodes where BOOTSTRAP_ANSIBLE_HOSTNAME_ is provided
#
# Ansible hosts - repeat this block as many times as you need,
# incrementing the last digit on the variable name for each node
#
#
# Configures your homelab nodes
homelab_hosts:
  - hostname: k8s-0
    groups: [kubernetes]
    control_node: true
  - hostname: k8s-1
    groups: [kubernetes]
    control_node: false
  - hostname: k8s-2
    groups: [kubernetes]
    control_node: false
